name: Java CI with Gradle

on:
  push:
    branches: [ "**" ] # Trigger on any branch push
  pull_request:
    branches: [ "**" ] # Trigger on any branch pull request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23' # Use Java 23
          distribution: 'temurin' # Eclipse Temurin distribution
          cache: gradle

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build the project
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # Run tests
      - name: Run tests
        run: ./gradlew test --no-daemon

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: build-artifacts
          path: build/libs/*.jar
